let suggestions = [
    "Formation Anglais",
    "Formation Français",
    "Formation Espagnol",
    "Formation Allemand",
    "Formation Excel",
    "Formation Word",
    "Formation Powerpoint",
    "Formation Informatique",
    "Formation Bureautique",
    "Formation InDesign",
    "Formation Photoshop",
    "Formation Illustrator",
    "Formation PAO",
    "Formation Secrétariat",
    "Formation Comptabilité",
    "Formation Hygiène Alimentaire",
    "Anglais",
    "Français",
    "Espagnol",
    "Allemand",
    "Excel",
    "Word",
    "Powerpoint",
    "Informatique",
    "Bureautique",
    "InDesign",
    "Photoshop",
    "Illustrator",
    "PAO",
    "Secrétariat",
    "Comptabilité",
    "Hygiène Alimentaire",
    "Hygiène",
    "Alimentaire",
    "HACCP",
];